### ISSUE TITLE
Améliorer les champs de saisie de montants

### ISSUE THREAD

**Issue by MattiSG** [betagouv/aides-jeunes#294]
- Vocalisés comme « bouton rotatif », incompréhensible.
- Pousse tous les usagers à déclarer un montant approximatif.

**Comment by fpagnoux** [comment]
We should check this out:
```css
/* to remove the "spin" button (which allows to increment the value) */
::-webkit-inner-spin-button {
    -webkit-appearance: none;
}
```
